#   server:
#   port: 因为会启动多个helpBuy-dataService, 所以端口号由用户自动设置，推荐 8001,8002,8003
 
spring:
  application:
    name: helpBuy-dataService
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
